name: Nix

on:
  pull_request:
  push:
    branches: [master]

jobs:
  develop:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: fcitx5-android
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Debug APK
        run: |
          nix develop .#noAS --command ./gradlew :app:assembleDebug
          nix develop .#noAS --command ./gradlew :assembleDebugPlugins

      - name: Upload app
        uses: actions/upload-artifact@v6
        with:
          name: app-${{ matrix.os }}
          path: app/build/outputs/apk/debug/

      - name: Pack plugins
        shell: bash
        run: |
          mkdir plugins-to-upload
          for i in $(ls plugin)
          do
            if [ -d "plugin/${i}" ]
            then
              mv "plugin/${i}/build/outputs/apk/debug" "plugins-to-upload/${i}"
            fi
          done

      - name: Upload plugins
        uses: actions/upload-artifact@v6
        with:
          name: plugins-${{ matrix.os }}
          path: plugins-to-upload
